# Símbolos de Yahoo Finance

VIX = "^VIX"
DXY = "DX-Y.NYB"
SP500 = "^GSPC"
NASDAQ = "^IXIC"
BITCOIN = "BTC-USD"
GOLD = "GC=F"
US10Y = "^TNX"
# Series FRED

FED_BALANCE = "WALCL"
REVERSE_REPO = "RRPONTSYD"
TGA = "WTREGEN"
M2 = "M2SL"

# Bancos centrales y divisas para el Global Liquidity Index
ECB_BALANCE = "ECBASSETSW"
ECB_DEPOSIT_RATE = "ECBDFR"
BOJ_BALANCE = "JPNASSETS"
# Tipos de cambio de mercado; la descarga histórica incluye reintentos.
EURUSD = "EURUSD=X"  # USD por EUR
USDJPY = "JPY=X"  # JPY por USD
USDCNY = "CNY=X"  # CNY por USD
FED_FUNDS_RATE = "DFF"
BOJ_CALL_RATE = "IRSTCI01JPM156N"

# Riesgo macroeconómico y de crédito
YIELD_CURVE_10Y2Y = "T10Y2Y"
HIGH_YIELD_SPREAD = "BAMLH0A0HYM2"
FINANCIAL_CONDITIONS = "NFCI"
US_CPI = "CPIAUCSL"
US_UNEMPLOYMENT = "UNRATE"
US_INDUSTRIAL_PRODUCTION = "INDPRO"
